---
version: '3.1'
services:
  database:
    image: mysql:8.0.30
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: asu
      MYSQL_USER: app
      MYSQL_PASSWORD: 12345
    ports:
      - "3308:3306"
  
  database-deployment:
    image: mysql:8.0.30
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: deployment
      MYSQL_USER: publisher
      MYSQL_PASSWORD: 12345
    ports:
      - "3309:3306"
